### ISSUE TITLE
Funcionamento 

### ISSUE THREAD

**Issue by PauloGama95** [rodrigopires/Itaucripto-NET#1]
Olá Rodrigo, tudo bem ?

Estou desenvolvendo uma aplicação para integração do Itau Shopline e gostaria de saber se o seu projeto ainda esta válido e posso utilizar ele no lugar da itaucripto.dll que o o itau disponibiliza.

um abraço.

**Comment by rodrigopires** [comment]
Olá. Utilizo o mesmo código até hoje em um projeto, e funciona normalmente. Essa lib é apenas um port para .NET da DLL original (feita em java se não me engano).

Abraço!
